export const LOAD_MUST_DATA = 'LOAD_MUST_DATA'
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'

export const SHOW_MORE_ARTICLES = 'SHOW_MORE_ARTICLES'

export const CHANGE_ARTICLE_GRADE = 'CHANGE_ARTICLE_GRADE'
export const ADD_ARTICLE_LOVE_NUMBER = 'ADD_ARTICLE_LOVE_NUMBER'
export const ADD_ARTICLE_SHARE_NUMBER = 'ADD_ARTICLE_SHARE_NUMBER'
