// data
export const LOAD_MUST_DATA = 'LOAD_MUST_DATA'
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'

export const SHOW_MORE_ARTICLES = 'SHOW_MORE_ARTICLES'

export const ADD_ARTICLE_LOVE_NUMBER = 'ADD_ARTICLE_LOVE_NUMBER'
export const ADD_ARTICLE_SHARE_NUMBER = 'ADD_ARTICLE_SHARE_NUMBER'

// contentTable
export const APPEAR_CONTENT_TABLE ='APPEAR_CONTENT_TABLE'
export const DISAPPEAR_CONTENT_TABLE ='DISAPPEAR_CONTENT_TABLE'

export const SHOW_CONTENT_TABLE ='SHOW_CONTENT_TABLE'
export const HIDDEN_CONTENT_TABLE ='HIDDEN_CONTENT_TABLE'

export const LOAD_CONTENT_TABLE_CONTENT ='LOAD_CONTENT_TABLE_CONTENT'
