export const MY_AVATOR_URL = ' http://7xkpdt.com1.z0.glb.clouddn.com/746baebb7f4be1cf71f9ae70be796ed7.png'
export const LOVE_ICONFONT = '&#xe603;'
export const ANCHOR_ICONFONT = '&#xe600;'
export const WEIBO_ICONFONT = '&#xe601;'
export const SHARE_ICONFONT = '&#xe602;'
export const EMAIL_ICONFONT = '&#xe604;'
export const ZHIHU_ICONFONT = '&#xe605;'
export const GITHUB_ICONFONT = '&#xe606;'
