export const INVALED_TAG_URL_TIP = '您访问的 url指向了不存在的 tag 页面'
export const ALL_ARTICLES_STR = '所有文章'

export const AUTHOR = '本文作者'
export const AUTHOR_NAME = 'SimplyY'
export const ARTICLE_DATE_LABEL_TEXT = '发布日期'
export const ARTICLE_DIFFCULT_LEVEL_TEXT = '本文难度'
export const EASY_TEXT = '简单'
export const NORMAL_TEXT = '中等'
export const DIFFICULT_TEXT = '困难'
